version: "3.0"
services:
  backend:
    container_name: search_backend
    build: 
      context: ./
      dockerfile: Backend.Dockerfile
    networks:
      - elk_elastic
    ports:
      - 8003:8000
  # frontend:
  #   container_name: search_frontend
  #   build: 
  #     context: ./
  #     dockerfile: Backend.Dockerfile
  #   networks:
  #     - elk_elastic
  #   depends_on:
  #     - backend
  #   ports:
  #     - 8502:8501
networks:
  elk_elastic:
    external: true